module.exports = [
  {
    plateIni: 'AAA0001',
    plateEnd: 'BEZ9999',
    stateName: 'Paraná',
    stateId: 'PR',
    sequence: '1',
  },
  {
    plateIni: 'BFA0001',
    plateEnd: 'GKI9999',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '1',
  },
  {
    plateIni: 'GKJ0001',
    plateEnd: 'HOK9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '1',
  },
  {
    plateIni: 'HOL0001',
    plateEnd: 'HQE9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '1',
  },
  {
    plateIni: 'HQF0001',
    plateEnd: 'HTW9999',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '1',
  },
  {
    plateIni: 'HTX0001',
    plateEnd: 'HZA9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '1',
  },
  {
    plateIni: 'HZB0001',
    plateEnd: 'IAP9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '1',
  },
  {
    plateIni: 'IAQ0001',
    plateEnd: 'JDO9999',
    stateName: 'Rio Grande do Sul',
    stateId: 'RS',
    sequence: '1',
  },
  {
    plateIni: 'JDP0001',
    plateEnd: 'JKR9999',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '1',
  },
  {
    plateIni: 'JKS0001',
    plateEnd: 'JSZ9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '1',
  },
  {
    plateIni: 'JTA0001',
    plateEnd: 'JWE9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '1',
  },
  {
    plateIni: 'JWF0001',
    plateEnd: 'JXY9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '1',
  },
  {
    plateIni: 'JXZ0001',
    plateEnd: 'KAU9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '1',
  },
  {
    plateIni: 'KAV0001',
    plateEnd: 'KFC9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '1',
  },
  {
    plateIni: 'KFD0001',
    plateEnd: 'KME9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '1',
  },
  {
    plateIni: 'KMF0001',
    plateEnd: 'LVE9999',
    stateName: 'Rio de Janeiro',
    stateId: 'RJ',
    sequence: '1',
  },
  {
    plateIni: 'LVF0001',
    plateEnd: 'LWQ9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '1',
  },
  {
    plateIni: 'LWR0001',
    plateEnd: 'MMM9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '1',
  },
  {
    plateIni: 'MMN0001',
    plateEnd: 'MOW9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '1',
  },
  {
    plateIni: 'MOX0001',
    plateEnd: 'MTZ9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '1',
  },
  {
    plateIni: 'MUA0001',
    plateEnd: 'MVK9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '1',
  },
  {
    plateIni: 'MVL0001',
    plateEnd: 'MXG9999',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '1',
  },
  {
    plateIni: 'MXH0001',
    plateEnd: 'MZM9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '1',
  },
  {
    plateIni: 'MZN0001',
    plateEnd: 'NAG9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '1',
  },
  {
    plateIni: 'NAH0001',
    plateEnd: 'NBA9999',
    stateName: 'Roraima',
    stateId: 'RR',
    sequence: '1',
  },
  {
    plateIni: 'NBB0001',
    plateEnd: 'NEH9999',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '1',
  },
  {
    plateIni: 'NEI0001',
    plateEnd: 'NFB9999',
    stateName: 'Amapá',
    stateId: 'AP',
    sequence: '1',
  },
  {
    plateIni: 'NFC0001',
    plateEnd: 'NGZ9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '2',
  },
  {
    plateIni: 'NHA0001',
    plateEnd: 'NHT9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '2',
  },
  {
    plateIni: 'NHU0001',
    plateEnd: 'NIX9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '2',
  },
  {
    plateIni: 'NIY0001',
    plateEnd: 'NJW9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '2',
  },
  {
    plateIni: 'NJX0001',
    plateEnd: 'NLU9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '3',
  },
  {
    plateIni: 'NLV0001',
    plateEnd: 'NMO9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '2',
  },
  {
    plateIni: 'NMP0001',
    plateEnd: 'NNI9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '3',
  },
  {
    plateIni: 'NNJ0001',
    plateEnd: 'NOH9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '2',
  },
  {
    plateIni: 'NOI0001',
    plateEnd: 'NPB9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '2',
  },
  {
    plateIni: 'NPC0001',
    plateEnd: 'NPQ9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '3',
  },
  {
    plateIni: 'NPR0001',
    plateEnd: 'NQK9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '2',
  },
  {
    plateIni: 'NQL0001',
    plateEnd: 'NRE9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '2',
  },
  {
    plateIni: 'NRF0001',
    plateEnd: 'NSD9999',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '2',
  },
  {
    plateIni: 'NSE0001',
    plateEnd: 'NTC9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '2',
  },
  {
    plateIni: 'NTD0001',
    plateEnd: 'NTW9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '2',
  },
  {
    plateIni: 'NTX0001',
    plateEnd: 'NUG9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '4',
  },
  {
    plateIni: 'NUH0001',
    plateEnd: 'NUL9999',
    stateName: 'Roraima',
    stateId: 'RR',
    sequence: '2',
  },
  {
    plateIni: 'NUM0001',
    plateEnd: 'NVF9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '3',
  },
  {
    plateIni: 'NVG0001',
    plateEnd: 'NVN9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '2',
  },
  {
    plateIni: 'NVO0001',
    plateEnd: 'NWR9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '4',
  },
  {
    plateIni: 'NWS0001',
    plateEnd: 'NXQ9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '4',
  },
  {
    plateIni: 'NXR0001',
    plateEnd: 'NXT9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '2',
  },
  {
    plateIni: 'NXU0001',
    plateEnd: 'NXW9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '2',
  },
  {
    plateIni: 'NXX0001',
    plateEnd: 'NYG9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '2',
  },
  {
    plateIni: 'NYH0001',
    plateEnd: 'NZZ9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '3',
  },
  {
    plateIni: 'OAA0001',
    plateEnd: 'OAO9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '3',
  },
  {
    plateIni: 'OAP0001',
    plateEnd: 'OBS9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '5',
  },
  {
    plateIni: 'OBT0001',
    plateEnd: 'OCA9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '3',
  },
  {
    plateIni: 'OCB0001',
    plateEnd: 'OCU9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '4',
  },
  {
    plateIni: 'OCV0001',
    plateEnd: 'ODT9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '2',
  },
  {
    plateIni: 'ODU0001',
    plateEnd: 'OEI9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '3',
  },
  {
    plateIni: 'OEJ0001',
    plateEnd: 'OES9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '3',
  },
  {
    plateIni: 'OET0001',
    plateEnd: 'OFH9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '3',
  },
  {
    plateIni: 'OFI0001',
    plateEnd: 'OFW9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '4',
  },
  {
    plateIni: 'OFX0001',
    plateEnd: 'OGG9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '4',
  },
  {
    plateIni: 'OGH0001',
    plateEnd: 'OHA9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '5',
  },
  {
    plateIni: 'OHB0001',
    plateEnd: 'OHK9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '3',
  },
  {
    plateIni: 'OHL0001',
    plateEnd: 'OHW9999',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '2',
  },
  {
    plateIni: 'OHX0001',
    plateEnd: 'OIQ9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '5',
  },
  {
    plateIni: 'OIR0001',
    plateEnd: 'OJQ9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '5',
  },
  {
    plateIni: 'OJR0001',
    plateEnd: 'OKC9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '3',
  },
  {
    plateIni: 'OKD0001',
    plateEnd: 'OKH9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '2',
  },
  {
    plateIni: 'OKI0001',
    plateEnd: 'OLG9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '4',
  },
  {
    plateIni: 'OLH0001',
    plateEnd: 'OLN9999',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '2',
  },
  {
    plateIni: 'OLO0001',
    plateEnd: 'OMH9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '3',
  },
  {
    plateIni: 'OMI0001',
    plateEnd: 'OOF9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '6',
  },
  {
    plateIni: 'OOG0001',
    plateEnd: 'OOU9999',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '3',
  },
  {
    plateIni: 'OOV0001',
    plateEnd: 'ORC9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '4',
  },
  {
    plateIni: 'ORD0001',
    plateEnd: 'ORM9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '4',
  },
  {
    plateIni: 'ORN0001',
    plateEnd: 'OSV9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '6',
  },
  {
    plateIni: 'OSW0001',
    plateEnd: 'OTZ9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '5',
  },
  {
    plateIni: 'OUA0001',
    plateEnd: 'OUE9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '4',
  },
  {
    plateIni: 'OUF0001',
    plateEnd: 'OVD9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '5',
  },
  {
    plateIni: 'OVE0001',
    plateEnd: 'OVF9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '3',
  },
  {
    plateIni: 'OVG0001',
    plateEnd: 'OVG9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '3',
  },
  {
    plateIni: 'OVH0001',
    plateEnd: 'OVL9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '4',
  },
  {
    plateIni: 'OVM0001',
    plateEnd: 'OVV9999',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '2',
  },
  {
    plateIni: 'OVW0001',
    plateEnd: 'OVY9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '5',
  },
  {
    plateIni: 'OVZ0001',
    plateEnd: 'OWG9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '4',
  },
  {
    plateIni: 'OWH0001',
    plateEnd: 'OXK9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '5',
  },
  {
    plateIni: 'OXL0001',
    plateEnd: 'OXL9999',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '3',
  },
  {
    plateIni: 'OXM0001',
    plateEnd: 'OXM9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '4',
  },
  {
    plateIni: 'OXN0001',
    plateEnd: 'OXN9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '5',
  },
  {
    plateIni: 'OXO0001',
    plateEnd: 'OXO9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '5',
  },
  {
    plateIni: 'OXP0001',
    plateEnd: 'OXP9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '4',
  },
  {
    plateIni: 'OXQ0001',
    plateEnd: 'OXZ9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '6',
  },
  {
    plateIni: 'OYA0001',
    plateEnd: 'OYC9999',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '3',
  },
  {
    plateIni: 'OYD0001',
    plateEnd: 'OYK9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '5',
  },
  {
    plateIni: 'OYL0001',
    plateEnd: 'OYZ9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '3',
  },
  {
    plateIni: 'OZA0001',
    plateEnd: 'OZA9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '7',
  },
  {
    plateIni: 'OZB0001',
    plateEnd: 'OZB9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '4',
  },
  {
    plateIni: 'OZC0001',
    plateEnd: 'OZV9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '6',
  },
  {
    plateIni: 'OZW0001',
    plateEnd: 'PBZ9999',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '3',
  },
  {
    plateIni: 'PCA0001',
    plateEnd: 'PED9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '4',
  },
  {
    plateIni: 'PEE0001',
    plateEnd: 'PFQ9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '5',
  },
  {
    plateIni: 'PFR0001',
    plateEnd: 'PGK9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '6',
  },
  {
    plateIni: 'PGL0001',
    plateEnd: 'PGU9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '7',
  },
  {
    plateIni: 'PGV0001',
    plateEnd: 'PGZ9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '8',
  },
  {
    plateIni: 'PHA0001',
    plateEnd: 'PHZ9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '5',
  },
  {
    plateIni: 'PIA0001',
    plateEnd: 'PIZ9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '6',
  },
  {
    plateIni: 'PJA0001',
    plateEnd: 'PLZ9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '7',
  },
  {
    plateIni: 'PMA0001',
    plateEnd: 'POZ9999',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '8',
  },
  {
    plateIni: 'PPA0001',
    plateEnd: 'PPZ9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '6',
  },
  {
    plateIni: 'PQA0001',
    plateEnd: 'PRZ9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '7',
  },
  {
    plateIni: 'PSA0001',
    plateEnd: 'PTZ9999',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '7',
  },
  {
    plateIni: 'PUA0001',
    plateEnd: 'PZZ9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '6',
  },
  {
    plateIni: 'QAA0001',
    plateEnd: 'QAZ9999',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '4',
  },
  {
    plateIni: 'QBA0001',
    plateEnd: 'QCZ9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '6',
  },
  {
    plateIni: 'QDA0001',
    plateEnd: 'QEZ9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '6',
  },
  {
    plateIni: 'QFA0001',
    plateEnd: 'QFZ9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '6',
  },
  {
    plateIni: 'QGA0001',
    plateEnd: 'QGZ9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '5',
  },
  {
    plateIni: 'QHA0001',
    plateEnd: 'QJZ9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '3',
  },
  {
    plateIni: 'QKA0001',
    plateEnd: 'QKM9999',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '4',
  },
  {
    plateIni: 'QKN0001',
    plateEnd: 'QKZ9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '5',
  },
  {
    plateIni: 'QLA0001',
    plateEnd: 'QLM9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '6',
  },
  {
    plateIni: 'QLN0001',
    plateEnd: 'QLT9999',
    stateName: 'Amapá',
    stateId: 'AP',
    sequence: '2',
  },
  {
    plateIni: 'QLU0001',
    plateEnd: 'QLZ9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '5',
  },
  {
    plateIni: 'QMA0001',
    plateEnd: 'QMP9999',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '6',
  },
  {
    plateIni: 'QMQ0001',
    plateEnd: 'QQZ9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '7',
  },
  {
    plateIni: 'QRA0001',
    plateEnd: 'QRA9999',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '4',
  },
  {
    plateIni: 'QRB0001',
    plateEnd: 'QRM9999',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '7',
  },
  {
    plateIni: 'QRN0001',
    plateEnd: 'QRZ9999',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '7',
  },
  {
    plateIni: 'QSA0001',
    plateEnd: 'QSM9999',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '7',
  },
  {
    plateIni: 'QSN0001',
    plateEnd: 'QSU9999',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '3',
  },
  {
    plateIni: 'QSV0001',
    plateEnd: 'QSZ9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '8',
  },
  {
    plateIni: 'QTA0001',
    plateEnd: 'QTJ9999',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '5',
  },
  {
    plateIni: 'QTK0001',
    plateEnd: 'QTS9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '4',
  },
  {
    plateIni: 'QTT0001',
    plateEnd: 'QTT9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '7',
  },
  {
    plateIni: 'QUA0001',
    plateEnd: 'QUZ9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '8',
  },
  {
    plateIni: 'QVA0001',
    plateEnd: 'QVZ9999',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '7',
  },
  {
    plateIni: 'QWA0001',
    plateEnd: 'QWF9999',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '5',
  },
  {
    plateIni: 'QWG0001',
    plateEnd: 'QWZ9999',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '8',
  },
  {
    plateIni: 'QXA0001',
    plateEnd: 'QYZ9999',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '9',
  },
  {
    plateIni: 'RGN0001',
    plateEnd: 'RGN9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '6',
  },
  {
    plateIni: 'RIO0001',
    plateEnd: 'RIO9999',
    stateName: 'Rio de Janeiro',
    stateId: 'RJ',
    sequence: '2',
  },
  {
    plateIni: 'SAV0001',
    plateEnd: 'SAV1000',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '2',
  },
];
