module.exports = [
  {
    plateIni: 'AAA0001',
    plateEnd: 'BEZ9Z99',
    stateName: 'Paraná',
    stateId: 'PR',
    sequence: '1',
  },
  {
    plateIni: 'BFA0001',
    plateEnd: 'GKI9Z99',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '1',
  },
  {
    plateIni: 'GKJ0001',
    plateEnd: 'HOK9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '1',
  },
  {
    plateIni: 'HOL0001',
    plateEnd: 'HQE9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '1',
  },
  {
    plateIni: 'HQF0001',
    plateEnd: 'HTW9Z99',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '1',
  },
  {
    plateIni: 'HTX0001',
    plateEnd: 'HZA9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '1',
  },
  {
    plateIni: 'HZB0001',
    plateEnd: 'IAP9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '1',
  },
  {
    plateIni: 'IAQ0001',
    plateEnd: 'JDO9Z99',
    stateName: 'Rio Grande do Sul',
    stateId: 'RS',
    sequence: '1',
  },
  {
    plateIni: 'JDP0001',
    plateEnd: 'JKR9Z99',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '1',
  },
  {
    plateIni: 'JKS0001',
    plateEnd: 'JSZ9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '1',
  },
  {
    plateIni: 'JTA0001',
    plateEnd: 'JWE9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '1',
  },
  {
    plateIni: 'JWF0001',
    plateEnd: 'JXY9Z99',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '1',
  },
  {
    plateIni: 'JXZ0001',
    plateEnd: 'KAU9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '1',
  },
  {
    plateIni: 'KAV0001',
    plateEnd: 'KFC9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '1',
  },
  {
    plateIni: 'KFD0001',
    plateEnd: 'KME9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '1',
  },
  {
    plateIni: 'KMF0001',
    plateEnd: 'LVE9Z99',
    stateName: 'Rio de Janeiro',
    stateId: 'RJ',
    sequence: '1',
  },
  {
    plateIni: 'LVF0001',
    plateEnd: 'LWQ9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '1',
  },
  {
    plateIni: 'LWR0001',
    plateEnd: 'MMM9Z99',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '1',
  },
  {
    plateIni: 'MMN0001',
    plateEnd: 'MOW9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '1',
  },
  {
    plateIni: 'MOX0001',
    plateEnd: 'MTZ9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '1',
  },
  {
    plateIni: 'MUA0001',
    plateEnd: 'MVK9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '1',
  },
  {
    plateIni: 'MVL0001',
    plateEnd: 'MXG9Z99',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '1',
  },
  {
    plateIni: 'MXH0001',
    plateEnd: 'MZM9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '1',
  },
  {
    plateIni: 'MZN0001',
    plateEnd: 'NAG9Z99',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '1',
  },
  {
    plateIni: 'NAH0001',
    plateEnd: 'NBA9Z99',
    stateName: 'Roraima',
    stateId: 'RR',
    sequence: '1',
  },
  {
    plateIni: 'NBB0001',
    plateEnd: 'NEH9Z99',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '1',
  },
  {
    plateIni: 'NEI0001',
    plateEnd: 'NFB9Z99',
    stateName: 'Amapá',
    stateId: 'AP',
    sequence: '1',
  },
  {
    plateIni: 'NFC0001',
    plateEnd: 'NGZ9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '2',
  },
  {
    plateIni: 'NHA0001',
    plateEnd: 'NHT9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '2',
  },
  {
    plateIni: 'NHU0001',
    plateEnd: 'NIX9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '2',
  },
  {
    plateIni: 'NIY0001',
    plateEnd: 'NJW9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '2',
  },
  {
    plateIni: 'NJX0001',
    plateEnd: 'NLU9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '3',
  },
  {
    plateIni: 'NLV0001',
    plateEnd: 'NMO9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '2',
  },
  {
    plateIni: 'NMP0001',
    plateEnd: 'NNI9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '3',
  },
  {
    plateIni: 'NNJ0001',
    plateEnd: 'NOH9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '2',
  },
  {
    plateIni: 'NOI0001',
    plateEnd: 'NPB9Z99',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '2',
  },
  {
    plateIni: 'NPC0001',
    plateEnd: 'NPQ9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '3',
  },
  {
    plateIni: 'NPR0001',
    plateEnd: 'NQK9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '2',
  },
  {
    plateIni: 'NQL0001',
    plateEnd: 'NRE9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '2',
  },
  {
    plateIni: 'NRF0001',
    plateEnd: 'NSD9Z99',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '2',
  },
  {
    plateIni: 'NSE0001',
    plateEnd: 'NTC9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '2',
  },
  {
    plateIni: 'NTD0001',
    plateEnd: 'NTW9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '2',
  },
  {
    plateIni: 'NTX0001',
    plateEnd: 'NUG9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '4',
  },
  {
    plateIni: 'NUH0001',
    plateEnd: 'NUL9Z99',
    stateName: 'Roraima',
    stateId: 'RR',
    sequence: '2',
  },
  {
    plateIni: 'NUM0001',
    plateEnd: 'NVF9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '3',
  },
  {
    plateIni: 'NVG0001',
    plateEnd: 'NVN9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '2',
  },
  {
    plateIni: 'NVO0001',
    plateEnd: 'NWR9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '4',
  },
  {
    plateIni: 'NWS0001',
    plateEnd: 'NXQ9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '4',
  },
  {
    plateIni: 'NXR0001',
    plateEnd: 'NXT9Z99',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '2',
  },
  {
    plateIni: 'NXU0001',
    plateEnd: 'NXW9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '2',
  },
  {
    plateIni: 'NXX0001',
    plateEnd: 'NYG9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '2',
  },
  {
    plateIni: 'NYH0001',
    plateEnd: 'NZZ9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '3',
  },
  {
    plateIni: 'OAA0001',
    plateEnd: 'OAO9Z99',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '3',
  },
  {
    plateIni: 'OAP0001',
    plateEnd: 'OBS9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '5',
  },
  {
    plateIni: 'OBT0001',
    plateEnd: 'OCA9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '3',
  },
  {
    plateIni: 'OCB0001',
    plateEnd: 'OCU9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '4',
  },
  {
    plateIni: 'OCV0001',
    plateEnd: 'ODT9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '2',
  },
  {
    plateIni: 'ODU0001',
    plateEnd: 'OEI9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '3',
  },
  {
    plateIni: 'OEJ0001',
    plateEnd: 'OES9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '3',
  },
  {
    plateIni: 'OET0001',
    plateEnd: 'OFH9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '3',
  },
  {
    plateIni: 'OFI0001',
    plateEnd: 'OFW9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '4',
  },
  {
    plateIni: 'OFX0001',
    plateEnd: 'OGG9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '4',
  },
  {
    plateIni: 'OGH0001',
    plateEnd: 'OHA9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '5',
  },
  {
    plateIni: 'OHB0001',
    plateEnd: 'OHK9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '3',
  },
  {
    plateIni: 'OHL0001',
    plateEnd: 'OHW9Z99',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '2',
  },
  {
    plateIni: 'OHX0001',
    plateEnd: 'OIQ9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '5',
  },
  {
    plateIni: 'OIR0001',
    plateEnd: 'OJQ9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '5',
  },
  {
    plateIni: 'OJR0001',
    plateEnd: 'OKC9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '3',
  },
  {
    plateIni: 'OKD0001',
    plateEnd: 'OKH9Z99',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '2',
  },
  {
    plateIni: 'OKI0001',
    plateEnd: 'OLG9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '4',
  },
  {
    plateIni: 'OLH0001',
    plateEnd: 'OLN9Z99',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '2',
  },
  {
    plateIni: 'OLO0001',
    plateEnd: 'OMH9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '3',
  },
  {
    plateIni: 'OMI0001',
    plateEnd: 'OOF9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '6',
  },
  {
    plateIni: 'OOG0001',
    plateEnd: 'OOU9Z99',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '3',
  },
  {
    plateIni: 'OOV0001',
    plateEnd: 'ORC9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '4',
  },
  {
    plateIni: 'ORD0001',
    plateEnd: 'ORM9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '4',
  },
  {
    plateIni: 'ORN0001',
    plateEnd: 'OSV9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '6',
  },
  {
    plateIni: 'OSW0001',
    plateEnd: 'OTZ9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '5',
  },
  {
    plateIni: 'OUA0001',
    plateEnd: 'OUE9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '4',
  },
  {
    plateIni: 'OUF0001',
    plateEnd: 'OVD9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '5',
  },
  {
    plateIni: 'OVE0001',
    plateEnd: 'OVF9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '3',
  },
  {
    plateIni: 'OVG0001',
    plateEnd: 'OVG9Z99',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '3',
  },
  {
    plateIni: 'OVH0001',
    plateEnd: 'OVL9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '4',
  },
  {
    plateIni: 'OVM0001',
    plateEnd: 'OVV9Z99',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '2',
  },
  {
    plateIni: 'OVW0001',
    plateEnd: 'OVY9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '5',
  },
  {
    plateIni: 'OVZ0001',
    plateEnd: 'OWG9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '4',
  },
  {
    plateIni: 'OWH0001',
    plateEnd: 'OXK9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '5',
  },
  {
    plateIni: 'OXL0001',
    plateEnd: 'OXL9Z99',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '3',
  },
  {
    plateIni: 'OXM0001',
    plateEnd: 'OXM9Z99',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '4',
  },
  {
    plateIni: 'OXN0001',
    plateEnd: 'OXN9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '5',
  },
  {
    plateIni: 'OXO0001',
    plateEnd: 'OXO9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '5',
  },
  {
    plateIni: 'OXP0001',
    plateEnd: 'OXP9Z99',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '4',
  },
  {
    plateIni: 'OXQ0001',
    plateEnd: 'OXZ9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '6',
  },
  {
    plateIni: 'OYA0001',
    plateEnd: 'OYC9Z99',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '3',
  },
  {
    plateIni: 'OYD0001',
    plateEnd: 'OYK9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '5',
  },
  {
    plateIni: 'OYL0001',
    plateEnd: 'OYZ9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '3',
  },
  {
    plateIni: 'OZA0001',
    plateEnd: 'OZA9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '7',
  },
  {
    plateIni: 'OZB0001',
    plateEnd: 'OZB9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '4',
  },
  {
    plateIni: 'OZC0001',
    plateEnd: 'OZV9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '6',
  },
  {
    plateIni: 'OZW0001',
    plateEnd: 'PBZ9Z99',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '3',
  },
  {
    plateIni: 'PCA0001',
    plateEnd: 'PED9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '4',
  },
  {
    plateIni: 'PEE0001',
    plateEnd: 'PFQ9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '5',
  },
  {
    plateIni: 'PFR0001',
    plateEnd: 'PGK9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '6',
  },
  {
    plateIni: 'PGL0001',
    plateEnd: 'PGU9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '7',
  },
  {
    plateIni: 'PGV0001',
    plateEnd: 'PGZ9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '8',
  },
  {
    plateIni: 'PHA0001',
    plateEnd: 'PHZ9Z99',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '5',
  },
  {
    plateIni: 'PIA0001',
    plateEnd: 'PIZ9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '6',
  },
  {
    plateIni: 'PJA0001',
    plateEnd: 'PLZ9Z99',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '7',
  },
  {
    plateIni: 'PMA0001',
    plateEnd: 'POZ9Z99',
    stateName: 'Ceará',
    stateId: 'CE',
    sequence: '8',
  },
  {
    plateIni: 'PPA0001',
    plateEnd: 'PPZ9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '6',
  },
  {
    plateIni: 'PQA0001',
    plateEnd: 'PRZ9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '7',
  },
  {
    plateIni: 'PSA0001',
    plateEnd: 'PTZ9Z99',
    stateName: 'Maranhão',
    stateId: 'MA',
    sequence: '7',
  },
  {
    plateIni: 'PUA0001',
    plateEnd: 'PZZ9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '6',
  },
  {
    plateIni: 'QAA0001',
    plateEnd: 'QAZ9Z99',
    stateName: 'Mato Grosso do Sul',
    stateId: 'MS',
    sequence: '4',
  },
  {
    plateIni: 'QBA0001',
    plateEnd: 'QCZ9Z99',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '6',
  },
  {
    plateIni: 'QDA0001',
    plateEnd: 'QEZ9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '6',
  },
  {
    plateIni: 'QFA0001',
    plateEnd: 'QFZ9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '6',
  },
  {
    plateIni: 'QGA0001',
    plateEnd: 'QGZ9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '5',
  },
  {
    plateIni: 'QHA0001',
    plateEnd: 'QJZ9Z99',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '3',
  },
  {
    plateIni: 'QKA0001',
    plateEnd: 'QKM9Z99',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '4',
  },
  {
    plateIni: 'QKN0001',
    plateEnd: 'QKZ9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '5',
  },
  {
    plateIni: 'QLA0001',
    plateEnd: 'QLM9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '6',
  },
  {
    plateIni: 'QLN0001',
    plateEnd: 'QLT9Z99',
    stateName: 'Amapá',
    stateId: 'AP',
    sequence: '2',
  },
  {
    plateIni: 'QLU0001',
    plateEnd: 'QLZ9Z99',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '5',
  },
  {
    plateIni: 'QMA0001',
    plateEnd: 'QMP9Z99',
    stateName: 'Sergipe',
    stateId: 'SE',
    sequence: '6',
  },
  {
    plateIni: 'QMQ0001',
    plateEnd: 'QQZ9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '7',
  },
  {
    plateIni: 'QRA0001',
    plateEnd: 'QRA9Z99',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '4',
  },
  {
    plateIni: 'QRB0001',
    plateEnd: 'QRM9Z99',
    stateName: 'Espírito Santo',
    stateId: 'ES',
    sequence: '7',
  },
  {
    plateIni: 'QRN0001',
    plateEnd: 'QRZ9Z99',
    stateName: 'Piauí',
    stateId: 'PI',
    sequence: '7',
  },
  {
    plateIni: 'QSA0001',
    plateEnd: 'QSM9Z99',
    stateName: 'Paraíba',
    stateId: 'PB',
    sequence: '7',
  },
  {
    plateIni: 'QSN0001',
    plateEnd: 'QSU9Z99',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '3',
  },
  {
    plateIni: 'QSV0001',
    plateEnd: 'QSZ9Z99',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '8',
  },
  {
    plateIni: 'QTA0001',
    plateEnd: 'QTJ9Z99',
    stateName: 'Rondônia',
    stateId: 'RO',
    sequence: '5',
  },
  {
    plateIni: 'QTK0001',
    plateEnd: 'QTS9Z99',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '4',
  },
  {
    plateIni: 'QTT0001',
    plateEnd: 'QTT9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '7',
  },
  {
    plateIni: 'QUA0001',
    plateEnd: 'QUZ9Z99',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '8',
  },
  {
    plateIni: 'QVA0001',
    plateEnd: 'QVZ9Z99',
    stateName: 'Pará',
    stateId: 'PA',
    sequence: '7',
  },
  {
    plateIni: 'QWA0001',
    plateEnd: 'QWF9Z99',
    stateName: 'Tocantins',
    stateId: 'TO',
    sequence: '5',
  },
  {
    plateIni: 'QWG0001',
    plateEnd: 'QWZ9Z99',
    stateName: 'Alagoas',
    stateId: 'AL',
    sequence: '8',
  },
  {
    plateIni: 'QYA0001',
    plateEnd: 'QYZ9Z99',
    stateName: 'Pernambuco',
    stateId: 'PE',
    sequence: '9',
  },
  {
    plateIni: 'RGN0001',
    plateEnd: 'RGN9Z99',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '6',
  },
  {
    plateIni: 'RIO0001',
    plateEnd: 'RIO9Z99',
    stateName: 'Rio de Janeiro',
    stateId: 'RJ',
    sequence: '2',
  },
  {
    plateIni: 'SAV0001',
    plateEnd: 'SAV1000',
    stateName: 'São Paulo',
    stateId: 'SP',
    sequence: '2',
  },
  {
    plateIni: 'QWM0001',
    plateEnd: 'QWQ9999',
    stateName: 'Acre',
    stateId: 'AC',
    sequence: '6',
  },
  {
    plateIni: 'QZA0001',
    plateEnd: 'QZZ9999',
    stateName: 'Amazonas',
    stateId: 'AM',
    sequence: '6',
  },
  {
    plateIni: 'RAA0001',
    plateEnd: 'RAJ9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '5',
  },
  {
    plateIni: 'QWR0001',
    plateEnd: 'QXZ9999',
    stateName: 'Minas Gerais',
    stateId: 'MG',
    sequence: '9',
  },
  {
    plateIni: 'RAK0001',
    plateEnd: 'RBJ9999',
    stateName: 'Mato Grosso',
    stateId: 'MT',
    sequence: '7',
  },
  {
    plateIni: 'RBK0001',
    plateEnd: 'RCN9999',
    stateName: 'Goiás',
    stateId: 'GO',
    sequence: '9',
  },
  {
    plateIni: 'RCO0001',
    plateEnd: 'RDR9999',
    stateName: 'Bahia',
    stateId: 'BA',
    sequence: '9',
  },
  {
    plateIni: 'RIP0001',
    plateEnd: 'RKV9999',
    stateName: 'Rio de Janeiro',
    stateId: 'RJ',
    sequence: '3',
  },
  {
    plateIni: 'RDS0001',
    plateEnd: 'REB9999',
    stateName: 'Santa Catarina',
    stateId: 'SC',
    sequence: '6',
  },
  {
    plateIni: 'REC0001',
    plateEnd: 'REZ9999',
    stateName: 'Distrito Federal',
    stateId: 'DF',
    sequence: '4',
  },
  {
    plateIni: 'RGE0001',
    plateEnd: 'RGM9999',
    stateName: 'Rio Grande do Norte',
    stateId: 'RN',
    sequence: '7',
  },
];
